
class CommandFailedError(Exception):
    pass

class ExitException(Exception):
    pass